---
- name: Create cluster
  ibm.cloudcollection.ibm_container_cluster:
    ibmcloud_api_key: "{{ lookup('file', '~/.ibmcloud/my_key_file') }}"
    name: "{{ cluster_name }}"
    datacenter: "{{ datacenter }}"
    hardware: shared
    machine_type: free
