name: Create Cluster

on: 
  workflow_dispatch:
    inputs:
      delete-cluster:
        description: 'Delete Old Cluster'
        required: false
        type: boolean
      create-cluster:
        description: 'Create New Cluster'
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup IBM Cloud API Key
      run: |
        mkdir -p ~/.ibmcloud
        echo ${{ secrets.IBM_CLOUD_API_KEY }} > ~/.ibmcloud/my_key_file

    - name: Install IBM Cloud Ansible Collection
      run: ansible-galaxy collection install ibm.cloudcollection

    - name: Delete Cluster
      if: ${{ inputs.delete-cluster }}
      run: ansible-playbook delete-cluster.yml

    - name: Create Cluster
      if: ${{ inputs.create-cluster }}
      run: ansible-playbook create-cluster.yml

    - name: Cluster Info
      run: ansible-playbook cluster-info.yml
