name: Create Cluster

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup IBM Cloud Key and Ansible Collection
      run: |
        mkdir -p ~/.ibmcloud
        echo ${{ secrets.IBM_CLOUD_API_KEY }} > ~/.ibmcloud/my_key_file

        ansible-galaxy collection install ibm.cloudcollection
